### ISSUE TITLE
Seeking for AVA captions

### ISSUE THREAD

**Issue by yipoh** [qowngus33/AVA_captioning_dataLodaer#1]
Dear author, Thank you for your contribution. Do you have the label file for the AVA_Captions database? I look forward to your reply. Thanks a lot.

**Comment by dacian7** [comment]
> Dear author, Thank you for your contribution. Do you have the label file for the AVA_Captions database? I look forward to your reply. Thanks a lot.

Hi @yipoh , have you found the AVA Captions dataset? The provided google drive seems empty in the original ICCVW'19 paper

**Comment by yipoh** [comment]
> > Dear author, Thank you for your contribution. Do you have the label file for the AVA_Captions database? I look forward to your reply. Thanks a lot.
> 
> Hi @yipoh , have you found the AVA Captions dataset? The provided google drive seems empty in the original ICCVW'19 paper

Thank you for your reply. I tried to reproduce the code, but it may not be very accurate. If you have this dataset, can you share it with me using your usual network disk? Thank you very much for your kind help!
